### ISSUE TITLE
Order confirmation

### ISSUE THREAD

**Issue by Makin-Things** [magic-blue-smoke/Dual-Edge-TPU-Adapter#15]
Hi Alexander, 

I placed an order with you and got an email letting me know I missed out filling in my last name. I replied twice to your emails, but am not sure you are getting them for some reason as you sent me an email saying I hadn't responded after I had, and have had no feedback to the follow up email.
In case you  haven't received my email my last name is Ratcliffe.

Cheers
Simon

**Comment by magic-blue-smoke** [comment]
Hi @Makin-Things 
I've found your reply in spam. Have no idea why it got there. Sorry for inconvenience, will ship your order soon.

**Comment by Makin-Things** [comment]
All good. Glad to get it sorted :)
