### ISSUE TITLE
Next shipment?

### ISSUE THREAD

**Issue by tempaone** [magic-blue-smoke/Dual-Edge-TPU-Adapter#22]
Hello,
When will the next shipment be available as it states all sold out and go on waiting list but no estimated time it will be available again.
Cheers

**Comment by magic-blue-smoke** [comment]
Hi. Boards are actually in stock, however due to recent changes selling those makes sense from 10pcs.
I'm working on several alternative options to have stable availability and no MOQ; I expect to have it ready for shipment in 4-6 weeks

**Comment by cegit55** [comment]
Thanks for the update - I am eagerly awaiting an m.2 B+M!

**Comment by steppel** [comment]
So how to order with MOQ 10 .. the page still shows out of stock

**Comment by cegit55** [comment]
Hi there @magic-blue-smoke,
Do you have any idea when the m.2 B+M adapter will become available?
I've been waiting (semi)patiently since the end of February.

**Comment by magic-blue-smoke** [comment]
@cegit55 @steppel lot of things changed, update is available here: magic-blue-smoke/Dual-Edge-TPU-Adapter/issues/8

**Comment by magic-blue-smoke** [comment]
m.2 2280 BM adapters are available for purchase now: https://github.com/magic-blue-smoke/Dual-Edge-TPU-Adapter/issues/8#issuecomment-1273867495
