### ISSUE TITLE
ASM1182 datasheet and temperature

### ISSUE THREAD

**Issue by kukkineko** [magic-blue-smoke/Dual-Edge-TPU-Adapter#49]
I got the m.2 Dual edge adapter and noticed that the IC is getting quite warm without any usage. Following questions

1. Is this normal behaviour?
2. Is there a datasheet for this IC (I couldnt find one)
3. Is there a command to check temperature or temperature to Tjmax
4. Does the IC shutdown if it gets too hot? If so what is its maximum temperature?

**Comment by magic-blue-smoke** [comment]
Hi @kukkineko 
Datasheet is under NDA.
Expected IC temperature is around 60C, while Tjmax is over 100C
Temperature measurement is not available
