### ISSUE TITLE
Dual Edge TPU Adapter - PCIe x1 Low Profile not showing up in /dev/

### ISSUE THREAD

**Issue by cdmichaelb** [magic-blue-smoke/Dual-Edge-TPU-Adapter#61]
Is there drivers or anything additional I need to see this? I couldn't find any instructions, but it doesn't just appear, either. I can't see any */apex.

I'm running Ubuntu.

- PRETTY_NAME="Ubuntu 22.04.4 LTS"
- NAME="Ubuntu"
- VERSION_ID="22.04"
- VERSION="22.04.4 LTS (Jammy Jellyfish)"
- VERSION_CODENAME=jammy
- ID=ubuntu
- ID_LIKE=debian

I ran lscpi as suggested in another post and I see these:

- 0a:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
- 0b:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU

Had an issue with the official guide. To get gasket driver I had to follow these [steps](https://github.com/google-coral/edgetpu/issues/822#issuecomment-2106374284):

```
git clone https://github.com/google/gasket-driver.git
cd gasket-driver/
debuild
sudo apt-get install devscripts build-essential lintian debhelper 
debuild -us -uc -tc -b
cd ..
sudo dpkg -i gasket-dkms_1.0-18_all.deb
```

**Comment by joshtwc** [comment]
What is the result of running 
`lsmod | grep apex`
and
`lspci -nnk | grep -A 3 TPU`

**Comment by cdmichaelb** [comment]
oops, sorry I got it to work with my latest edit, I should've closed but forgot
